// Crossing Moving Averages
//
// This strategy is based in two moving averages, one faster than the
// other. When the faster moving average cross over the slower, it could
// be interpreted as an uptrend movement and it can be a good time to
// buy. In the same way, when the faster moving average cross under the
// slower, it could be interpreted as a downtrend movement in the
// market, signing a good time to sell.
//
// (2025) Jaime Lopez <https://github.com/jailop/>

//@version=6
indicator("Crossing Moving Averages", overlay=true)

faster = input.int(9, "Fast Moving Average Period")
slower = input.int(21, "Slow Moving Average Period")
avgType = input.string("EMA", "Moving Average Type", options=["SMA", "EMA"])

fastMA = avgType == "EMA" ? ta.ema(close, faster) : ta.ema(close, faster)
slowMA = avgType == "SMA" ? ta.sma(close, slower) : ta.sma(close, slower)

plot(fastMA, color=color.orange, title="Fast MA", linewidth = 2)
plot(slowMA, color=color.blue, title="Slow MA", linewidth = 2)

buySignal = ta.crossover(fastMA, slowMA)
sellSignal = ta.crossunder(fastMA, slowMA)

plotshape(buySignal, title="Buy", location=location.belowbar, color=color.green, style=shape.labelup, text="Buy")
plotshape(sellSignal, title="Sell", location=location.abovebar, color=color.red, style=shape.labeldown, text="Sell")

alertcondition(buySignal, title="Buy Alert", message="Faster MA above")
alertcondition(sellSignal, title="Sell Alert", message="Fast MA below")
